### ISSUE TITLE
Trouble with make mobile-install

### ISSUE THREAD

**Issue by boxofrabbits** [master-hax/pixel-backup-gang#1]
Hey guys
Really excited about this project. 

I'm having some basic trouble with the adb command "make mobile-install"
It doesn't seem to be in anyway recognised as a command with platform-tools. 
I'm definitely doing something silly, would greatly appreciate a point int he right direction.

**Comment by master-hax** [comment]
`mobile-install` is a [target](https://github.com/master-hax/pixel-backup-gang/blob/7ad165ba2e43210191c23fcb4341eaab04e49db9/Makefile#L28) in the Makefile.

if you are not using a linux computer or you don't want to install `Make`, you can manually copy the scripts to the pixel.

**Comment by boxofrabbits** [comment]
Thanks for your reply. I'm so close to getting this to work. 

I'm currently getting mnt/my_drive : No such file of directory when trying to mount the ext4 drive.

Do you have any ideas? 

Also I don't think I quite undersatdn the difference between show_devices and find_device. I've been using show_devices to find my UUID

**Comment by master-hax** [comment]
do you mind sharing the command you're running?

**Comment by master-hax** [comment]
i should look into automating this.

**Comment by boxofrabbits** [comment]
Hello! Sorry for not getting back to you. I got it working and actually made a little menu script to make things easier. 
[menu.txt](https://github.com/user-attachments/files/15795408/menu.txt)

You just need to

chmod +x /path/to/menu.sh

Prior and if you're on PC then Dos2Unix.
