### ISSUE TITLE
Issue in mounting usb stick (ext4)

### ISSUE THREAD

**Issue by shadww** [master-hax/pixel-backup-gang#11]
Hi.

When trying to run the /mount_ext4.sh, I get an invalid argument error.

![image](https://github.com/user-attachments/assets/4eb6a898-2fe9-4e9a-933e-5880b1ebc69f)

The drive is formatted and detected on /dev/block/sdg1

![image](https://github.com/user-attachments/assets/cbca5fbc-8afa-4a31-84d1-53b64a7139b9)

All commands run on termux with root granted by Magisik.
Using pixel XL (marlin).

edit: I formated using gparted on linux.

edit2: It works now. I used the minitool partition software on windows and the stick was recognized this time.

I am wondering what is the correct way to format the USB on linux to ext4

**Comment by master-hax** [comment]
from a linux computer with root access, identify the block device with `lsblk` then run
```
mkfs -t ext4 <block device>
```

**Comment by shadww** [comment]
I tried formatting in Linux using the mkfs command, which now gives me the previous invalid error. Formatting with the Windows tool still works.

**Comment by master-hax** [comment]
Just checking, you used "sudo" when running the "mkfs" command right?

**Comment by shadww** [comment]
Yes I used sudo.

**Comment by master-hax** [comment]
i'll mark this as closed since you got it to work and the issue was the formatting step, thanks

**Comment by master-hax** [comment]
i'll mark this as closed since you got it to work and the issue was the formatting step, thanks
