### ISSUE TITLE
inaccessible or not found

### ISSUE THREAD

**Issue by KAPABLE-K** [master-hax/pixel-backup-gang#12]
I'm currently facing an issue and I can't seem to figure it out at this point.

![Screenshot_20240905-171351](https://github.com/user-attachments/assets/3169ab5f-89d9-41b8-8003-4c61ba7c7543)

**Comment by Oblivivious** [comment]
See if issue #2 is any help, I made a kind of mess with the instructions. Make sure you have formatted your drive to ext4 if you using windows use a software called minitool partition wizard

**Comment by master-hax** [comment]
`start_global_shell.sh` puts you into the root directory

you need to navigate back to `/data/data/com.termux/files/home/pixel-backup-gang`

**Comment by KAPABLE-K** [comment]
Thanks, I actually did use that tool and format my drive.

I was able to figure it out from your post.

sh -c "$(curl -fSs https://raw.githubusercontent.com/master-hax/pixel-backup-gang/master/install.sh)"
cd /data/data/com.termux/files/home/pixel-backup-gang
./start_global_shell.sh
cd /data/data/com.termux/files/home/pixel-backup-gang
./mount_ext4.sh /dev/block/sdi1

After I did
./start_global_shell.sh

I did not know I had to go back to the folder by doing 
cd /data/data/com.termux/files/home/pixel-backup-gang

Then mount the drive, after doing that I was finally able to mount the drive, thanks!

**Comment by KAPABLE-K** [comment]
> `start_global_shell.sh` puts you into the root directory
> 
> you need to navigate back to `/data/data/com.termux/files/home/pixel-backup-gang`

After I mount the drive and restart the device, does the drive stay mounted or do I need to rerun the commands?

**Comment by master-hax** [comment]
it stays mounted until the unmounting script is run or the device is restarted
