### ISSUE TITLE
Has root, but start_global_shell.sh throws a "Can't Execute: Permission Denied" error

### ISSUE THREAD

**Issue by toyssamurai** [master-hax/pixel-backup-gang#16]
I rooted using Magisk, and verified that I have root access. I downloaded the scripts to /storage, then run:

`./start_global_shell.sh`

But I got the following error:

`/system/bin/sh: ./start_global_shell.sh: can't execute: Permission denied`

Below is everything I have done through ADB:

```
sailfish:/ $ cd /storage/pixel-backup-gang
sailfish:/storage/pixel-backup-gang $ ls -l
ls: ./start_global_shell.sh: Permission denied
ls: ./disable_tcp_debugging.sh: Permission denied
ls: ./enable_tcp_debugging.sh: Permission denied
ls: ./show_devices.sh: Permission denied
ls: ./find_device.sh: Permission denied
ls: ./unmount.sh: Permission denied
ls: ./mount_ext4.sh: Permission denied
total 0
1|sailfish:/storage/pixel-backup-gang $ su
sailfish:/storage/pixel-backup-gang # ls -l
total 28
-rwxr-xr-x 1 root root  336 2024-06-16 02:35 disable_tcp_debugging.sh
-rwxr-xr-x 1 root root  364 2024-06-16 02:35 enable_tcp_debugging.sh
-rwxr-xr-x 1 root root  448 2024-06-16 02:35 find_device.sh
-rwxr-xr-x 1 root root 1111 2024-06-16 02:35 mount_ext4.sh
-rwxr-xr-x 1 root root  319 2024-06-16 02:35 show_devices.sh
-rwxr-xr-x 1 root root  551 2024-06-16 02:35 start_global_shell.sh
-rwxr-xr-x 1 root root  558 2024-06-16 02:35 unmount.sh
sailfish:/storage/pixel-backup-gang # ./start_global_shell.sh
/system/bin/sh: ./start_global_shell.sh: can't execute: Permission denied
126|sailfish:/storage/pixel-backup-gang #
```

**Comment by master-hax** [comment]
you didn't make the scripts executable with `chmod`

**Comment by Oblivivious** [comment]
I believe you need su to have permission.
I made instructions at #2

**Comment by master-hax** [comment]
They are already running as root - notice the `#` prompt

**Comment by toyssamurai** [comment]
> you didn't make the scripts executable with `chmod`

I did (in a previous section):

`-rwxr-xr-x 1 root root  551 2024-06-16 02:35 start_global_shell.sh`

> I believe you need su to have permission.

I am running as root already. The first `ls -l` gave me permission denied, then I did `su`, and the second `ls -l` worked without problems.

**Comment by toyssamurai** [comment]
I got it to work. I didn't install with `su`, and it appears that even I `chmod` afterward, `start_global_shell.sh` won't work.

**Comment by toyssamurai** [comment]
It appears that if installation isn't done with `su`, even if you `chmod +x` afterward, the scripts still won't run.

**Comment by master-hax** [comment]
`chmod +x` is part of the installation process, which can't be done without root. so yes, the installation does need root.

the two automated installation methods invoke `su` directly, so if you use one of those methods, you won't have this problem.
