### ISSUE TITLE
SDCARDFS mount is failing with error "No such device"

### ISSUE THREAD

**Issue by brosahay** [master-hax/pixel-backup-gang#26]
I followed the steps, both in the script and manually, but facing the issue for this command
```
mount -t sdcardfs -o nosuid,nodev,noexec,noatime,gid=9997 <folder-on-drive> <mount-point>
```
But the device is accessible in the location that I have mentioned on step `mount -t ext4 -o nosuid,nodev,noexec,noatime BLOCK_DEV MOUNT_POINT`, here I can browse the disk and see all that it has. Alternatively, I tried binding to a location in the `/sdcard/usb0` and I was able to explore the disk using file explorer too, but google photos will not recognize it. Any help ?

I am using a pixel 5a, running android 14 and rooted using magisk

**Comment by master-hax** [comment]
What is the error message?

**Comment by brosahay** [comment]
Just says No such device when I try to run the mentioned command. Not really sure why.

**Comment by master-hax** [comment]
not sure. note that this is only tested on the OG pixels. can you please provide the output of `cat /proc/filesystems`?

**Comment by brosahay** [comment]
yes, I did notice that. But theoretically it should work, hence was trying. 
Attaching the output from the above command.
```
nodev	sysfs
nodev	rootfs
nodev	tmpfs
nodev	bdev
nodev	proc
nodev	cpuset
nodev	cgroup
nodev	cgroup2
nodev	configfs
nodev	tracefs
nodev	sockfs
nodev	bpf
nodev	pipefs
nodev	ramfs
nodev	devpts
	ext3
	ext2
	ext4
	vfat
nodev	ecryptfs
	fuseblk
nodev	fuse
nodev	fusectl
nodev	overlay
	f2fs
nodev	selinuxfs
nodev	binder
nodev	pstore
nodev	incremental-fs
nodev	functionfs
```

**Comment by master-hax** [comment]
your device's kernel doesn't support the `sdcardfs` filesystem since it isn't in that list. newer versions of android must do things differently.

**Comment by brosahay** [comment]
okay, closing this thread. Hoping to find a way to make it work on newer android
