### ISSUE TITLE
How are you able to connect a usb c hub to the pixel in the image?

### ISSUE THREAD

**Issue by wolfdael** [master-hax/pixel-backup-gang#27]
I have a pixel XL and a wavlink usb c hub. When connected for charging, it doesn't work. I am not yet rooted. 

Should I be rooted to enable charging, ethernet? Or is it that only some usb c hubs work? Which one do you have?

**Comment by brosahay** [comment]
USB hub having PD pass-through should be able to charge and do the rest functions as a hub

**Comment by master-hax** [comment]
Yes, make sure it has USB PD. There's some existing discussion here: https://github.com/master-hax/pixel-backup-gang/issues/6

**Comment by master-hax** [comment]
i'll close this issue since we haven't heard back in a while. feel free to reopen if needed.
